version: "3.7"

services:
  frontend:
    container_name: bootcamp_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
  backend:
    container_name: bootcamp_backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    dns:
      - 8.8.8.8
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env